name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          
      - run: npm install && npm install -g @lhci/cli
      - run: npm run build
      - run: lhci collect
      - run: lhci upload
        env:
            LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}